/**
 * Validation utilities for input parameters.
 */

/**
 * Validate that a string is a valid UUID format (v1-v5).
 *
 * Session IDs in DocImp are UUIDs generated by the CLI layer.
 * This validation ensures commands receive properly formatted IDs
 * and provides clear error messages for malformed input.
 *
 * @param sessionId - The session ID string to validate
 * @returns True if valid UUID format, false otherwise
 */
export function isValidUuid(sessionId: string): boolean {
  // UUID v1-v5 pattern: xxxxxxxx-xxxx-[1-5]xxx-[89ab]xxx-xxxxxxxxxxxx
  const uuidRegex =
    /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
  return uuidRegex.test(sessionId);
}
